### ISSUE TITLE
Upgrade AMRFinderPlus to version 3.12.8 and DB to version 2024-01-31.1

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#334]
:cool:

https://github.com/ncbi/amr/releases/tag/amrfinder_v3.12.8

**Comment by kapsakcj** [comment]
I just added a docker image for this to StaPH-B/docker-builds. Image will be available on dockerhub & quay momentarily.

We will need to copy the image over to our GAR & update the defaults in the WDL task (and at the same time, revisit the list of `--organism` options and update merlin_magic subwf, GAMBIT task (for assigning merlin_tag), and update the amrfinder WDL command block to accept the new organism options.

This issue is related to #129 which documents SOME of the new organisms, but we need to do a thorough check on the list of supported organisms from `amrfinder`. Check this docs page, but double check release notes to ensure we capture them all (sometimes the docs lag behind the software) https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option

**Comment by sage-wright** [comment]
Duplicated in #129, closing this one
